[general]
import = ["~/.config/alacritty/dracula.toml"]
live_config_reload = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

# [[keyboard.bindings]]
# chars = "\rcls\r"
# key = "L"
# mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
# auto_scroll = true
history = 5000

# [shell]
# program = "bash"

[window]
dynamic_padding = false

[window.padding]
x = 10
y = 10
